name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . 
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/tqs-ph-backend:latest
          file: ./Dockerfile # Ensure the path to the Dockerfile is correct

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/tqs-ph-backend:latest
          service: polloshermanos-backend
          region: europe-central2
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap
