name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Authenticate to Google Cloud
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${{ runner.temp }}/gcloud.json

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ runner.temp }}/gcloud.json
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/tqs-ph-backend:latest

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/tqs-ph-backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy tqs-ph-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/tqs-ph-backend:latest \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
